import type React from 'react';

// CTA Button Template definitions
// Shared between admin editor and public rendering

export type CTACategory = 'basic' | 'cv' | 'industry' | 'design';

export interface CTATemplate {
    name: string;
    label: string;
    category: CTACategory;
    background: string;
    color: string;
    borderRadius: string;
    fontWeight: string;
    padding: string;
    fontSize: number;
    animation: 'none' | 'pulse' | 'bounce';
    border?: string;
    boxShadow?: string;
    icon?: 'line' | 'phone' | 'mail';
    positionMode?: 'absolute' | 'fixed_bottom' | 'fixed_right' | 'fixed_left';
    letterSpacing?: string;
    textShadow?: string;
}

export const CTA_CATEGORIES: Record<CTACategory, string> = {
    basic: '基本',
    cv: 'CV特化',
    industry: '業種別',
    design: 'デザイン',
};

export const CTA_TEMPLATES: Record<string, CTATemplate> = {
    // ========== 基本 ==========
    basic_solid: {
        name: 'ベーシック',
        label: '今すぐ申し込む',
        category: 'basic',
        background: '#2563eb',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 32px',
        fontSize: 16,
        animation: 'none',
    },
    pill_soft: {
        name: 'やわらかピル',
        label: 'お問い合わせ',
        category: 'basic',
        background: '#f59e0b',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '12px 36px',
        fontSize: 15,
        animation: 'none',
    },
    outline_simple: {
        name: 'アウトライン',
        label: '詳しく見る',
        category: 'basic',
        background: 'transparent',
        color: '#1f2937',
        borderRadius: '8px',
        fontWeight: '600',
        padding: '12px 28px',
        fontSize: 15,
        border: '2px solid #1f2937',
        animation: 'none',
    },
    icon_arrow: {
        name: '矢印付き',
        label: '今すぐチェック →',
        category: 'basic',
        background: '#111827',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 32px',
        fontSize: 15,
        animation: 'none',
    },
    outline_white: {
        name: '白アウトライン',
        label: 'もっと見る',
        category: 'basic',
        background: 'transparent',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: '600',
        padding: '12px 32px',
        fontSize: 15,
        border: '2px solid #ffffff',
        animation: 'none',
    },
    minimal_text: {
        name: 'ミニマルテキスト',
        label: '詳細はこちら →',
        category: 'basic',
        background: 'transparent',
        color: '#2563eb',
        borderRadius: '0px',
        fontWeight: '600',
        padding: '8px 4px',
        fontSize: 15,
        border: 'none',
        boxShadow: 'none',
        animation: 'none',
    },

    // ========== CV特化（心理トリガー） ==========
    gradient_strong: {
        name: 'グラデーション',
        label: '無料で始める',
        category: 'cv',
        background: 'linear-gradient(135deg, #ef4444, #f97316)',
        color: '#ffffff',
        borderRadius: '12px',
        fontWeight: 'bold',
        padding: '16px 40px',
        fontSize: 17,
        animation: 'none',
    },
    gradient_pulse: {
        name: '緊急パルス',
        label: '期間限定！今すぐ申し込む',
        category: 'cv',
        background: 'linear-gradient(90deg, #4f46e5, #9333ea)',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 16,
        animation: 'pulse',
    },
    urgency_red: {
        name: '緊急感レッド',
        label: '残りわずか！今すぐ予約',
        category: 'cv',
        background: '#dc2626',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '16px 36px',
        fontSize: 16,
        animation: 'pulse',
        boxShadow: '0 0 20px rgba(220,38,38,0.4)',
    },
    free_trial: {
        name: '無料訴求',
        label: '＼ 無料体験はこちら ／',
        category: 'cv',
        background: 'linear-gradient(135deg, #059669, #10b981)',
        color: '#ffffff',
        borderRadius: '12px',
        fontWeight: 'bold',
        padding: '16px 36px',
        fontSize: 16,
        animation: 'none',
    },
    limited_offer: {
        name: '限定オファー',
        label: '【先着50名】特別価格で申し込む',
        category: 'cv',
        background: 'linear-gradient(135deg, #b45309, #d97706)',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '16px 36px',
        fontSize: 15,
        animation: 'bounce',
        boxShadow: '0 4px 20px rgba(217,119,6,0.3)',
    },
    guarantee: {
        name: '安心保証',
        label: '30日間返金保証付きで申し込む',
        category: 'cv',
        background: '#1e40af',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '16px 36px',
        fontSize: 15,
        animation: 'none',
        border: '2px solid #93c5fd',
    },
    fixed_bottom_bar: {
        name: '固定バー',
        label: 'お申し込みはこちら',
        category: 'cv',
        background: '#dc2626',
        color: '#ffffff',
        borderRadius: '0px',
        fontWeight: 'bold',
        padding: '16px 40px',
        fontSize: 16,
        animation: 'none',
        positionMode: 'fixed_bottom',
    },
    fixed_bottom_gradient: {
        name: '固定バー（グラデ）',
        label: '今すぐ無料で始める →',
        category: 'cv',
        background: 'linear-gradient(90deg, #7c3aed, #db2777)',
        color: '#ffffff',
        borderRadius: '0px',
        fontWeight: 'bold',
        padding: '16px 40px',
        fontSize: 16,
        animation: 'none',
        positionMode: 'fixed_bottom',
    },

    fixed_right_bar: {
        name: '右固定バー',
        label: 'エントリーはこちら ＞',
        category: 'cv',
        background: '#dc2626',
        color: '#ffffff',
        borderRadius: '8px 0 0 8px',
        fontWeight: 'bold',
        padding: '20px 12px',
        fontSize: 14,
        animation: 'none',
        positionMode: 'fixed_right',
        letterSpacing: '0.1em',
    },
    fixed_right_gradient: {
        name: '右固定（グラデ）',
        label: 'お問い合わせ ＞',
        category: 'cv',
        background: 'linear-gradient(180deg, #7c3aed, #db2777)',
        color: '#ffffff',
        borderRadius: '8px 0 0 8px',
        fontWeight: 'bold',
        padding: '20px 12px',
        fontSize: 14,
        animation: 'none',
        positionMode: 'fixed_right',
    },
    fixed_left_bar: {
        name: '左固定バー',
        label: 'お問い合わせ',
        category: 'cv',
        background: '#1e40af',
        color: '#ffffff',
        borderRadius: '0 8px 8px 0',
        fontWeight: 'bold',
        padding: '20px 12px',
        fontSize: 14,
        animation: 'none',
        positionMode: 'fixed_left',
        letterSpacing: '0.1em',
    },

    // ========== 業種別 ==========
    line_green: {
        name: 'LINE誘導',
        label: 'LINEで相談する',
        category: 'industry',
        background: '#06C755',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 32px',
        fontSize: 15,
        icon: 'line',
        animation: 'none',
    },
    clinic_reserve: {
        name: '整体・クリニック',
        label: '初回限定！予約する',
        category: 'industry',
        background: 'linear-gradient(135deg, #0891b2, #06b6d4)',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 15,
        animation: 'none',
    },
    beauty_reserve: {
        name: '美容・サロン',
        label: 'カウンセリング予約 →',
        category: 'industry',
        background: 'linear-gradient(135deg, #ec4899, #f472b6)',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 15,
        animation: 'none',
    },
    restaurant_book: {
        name: '飲食・レストラン',
        label: '席を予約する',
        category: 'industry',
        background: '#b91c1c',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 15,
        animation: 'none',
    },
    realestate_contact: {
        name: '不動産',
        label: '無料査定を依頼する',
        category: 'industry',
        background: '#1e3a5f',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 15,
        animation: 'none',
    },
    phone_call: {
        name: '電話予約',
        label: '今すぐ電話する',
        category: 'industry',
        background: '#16a34a',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 32px',
        fontSize: 15,
        icon: 'phone',
        animation: 'none',
    },
    mail_contact: {
        name: 'メール問い合わせ',
        label: 'メールで相談する',
        category: 'industry',
        background: '#4f46e5',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 32px',
        fontSize: 15,
        icon: 'mail',
        animation: 'none',
    },
    ec_cart: {
        name: 'EC・通販',
        label: 'カートに入れる',
        category: 'industry',
        background: '#ea580c',
        color: '#ffffff',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 16,
        animation: 'none',
    },

    // ========== デザインバリエーション ==========
    neon_glow: {
        name: 'ネオン',
        label: 'Get Started',
        category: 'design',
        background: 'transparent',
        color: '#22d3ee',
        borderRadius: '8px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 16,
        border: '2px solid #22d3ee',
        boxShadow: '0 0 15px rgba(34,211,238,0.5), inset 0 0 15px rgba(34,211,238,0.1)',
        animation: 'none',
    },
    glass_light: {
        name: 'ガラス（ライト）',
        label: 'お申し込み',
        category: 'design',
        background: 'rgba(255,255,255,0.25)',
        color: '#ffffff',
        borderRadius: '12px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 15,
        border: '1px solid rgba(255,255,255,0.4)',
        boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
        animation: 'none',
    },
    glass_dark: {
        name: 'ガラス（ダーク）',
        label: '詳しく見る',
        category: 'design',
        background: 'rgba(0,0,0,0.4)',
        color: '#ffffff',
        borderRadius: '12px',
        fontWeight: '600',
        padding: '14px 36px',
        fontSize: 15,
        border: '1px solid rgba(255,255,255,0.2)',
        boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
        animation: 'none',
    },
    threed_shadow: {
        name: '3D風',
        label: '今すぐ始める',
        category: 'design',
        background: '#6366f1',
        color: '#ffffff',
        borderRadius: '12px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 16,
        border: 'none',
        boxShadow: '0 6px 0 #4338ca, 0 8px 20px rgba(99,102,241,0.3)',
        animation: 'none',
    },
    rainbow_gradient: {
        name: 'レインボー',
        label: '無料で試す',
        category: 'design',
        background: 'linear-gradient(90deg, #f43f5e, #f59e0b, #22c55e, #3b82f6, #8b5cf6)',
        color: '#ffffff',
        borderRadius: '999px',
        fontWeight: 'bold',
        padding: '14px 36px',
        fontSize: 16,
        animation: 'none',
        textShadow: '0 1px 2px rgba(0,0,0,0.2)',
    },
    handwritten: {
        name: '手書き風',
        label: 'ここをタップ！',
        category: 'design',
        background: '#fef3c7',
        color: '#92400e',
        borderRadius: '4px',
        fontWeight: 'bold',
        padding: '12px 28px',
        fontSize: 16,
        border: '3px dashed #d97706',
        boxShadow: '3px 3px 0px #d97706',
        animation: 'none',
    },
    luxury_gold: {
        name: 'ラグジュアリー',
        label: 'ご予約はこちら',
        category: 'design',
        background: 'linear-gradient(135deg, #78350f, #b45309, #d97706)',
        color: '#fef3c7',
        borderRadius: '0px',
        fontWeight: '600',
        padding: '16px 48px',
        fontSize: 15,
        border: '1px solid #d97706',
        letterSpacing: '0.15em',
        animation: 'none',
    },
    dark_premium: {
        name: 'ダークプレミアム',
        label: 'Apply Now',
        category: 'design',
        background: '#0f172a',
        color: '#e2e8f0',
        borderRadius: '4px',
        fontWeight: '600',
        padding: '16px 48px',
        fontSize: 15,
        border: '1px solid #334155',
        letterSpacing: '0.1em',
        animation: 'none',
    },
};

// Helper: get CSS style object from template
export function getTemplateStyle(templateId: string): React.CSSProperties {
    const t = CTA_TEMPLATES[templateId];
    if (!t) return {};

    const isGradient = t.background.includes('gradient');
    const isRgba = t.background.includes('rgba');

    return {
        background: (isGradient || isRgba) ? t.background : undefined,
        backgroundColor: (isGradient || isRgba) ? undefined : t.background,
        color: t.color,
        borderRadius: t.borderRadius,
        fontWeight: t.fontWeight,
        padding: t.padding,
        fontSize: `${t.fontSize}px`,
        border: t.border || 'none',
        boxShadow: t.boxShadow ?? '0 4px 14px rgba(0,0,0,0.15)',
        cursor: 'pointer',
        display: 'inline-block',
        textAlign: 'center' as const,
        textDecoration: 'none',
        whiteSpace: 'nowrap' as const,
        letterSpacing: t.letterSpacing,
        textShadow: t.textShadow,
    };
}
